### ISSUE TITLE
How to fix Debug on Login?

### ISSUE THREAD

**Issue by Blingx** [jaurez/Oganza-Server#2]
When longing in i get an immediate debug, Do you know what Client Modifications i need to make? Thanks in Advance!

**Comment by jaurez** [comment]
Use the client that is available for download.
Sorry my english!

**Comment by Blingx** [comment]
Thanks you for the quick reply!
Now I am getting an "Invalid Client Login" Error in the Server Console. Any ideas? I will continue to troubleshoot in the meantime!

**Comment by jaurez** [comment]
The client is on the topic to download, just use it. 11.46

**Comment by jaurez** [comment]
Use login.php on your site

**Comment by jaurez** [comment]
If you are using all new files, it should work correctly

**Comment by Blingx** [comment]
Getting Same error, using Uniserver/Znote thats the only difference. Oh well seems it only works for some people

**Comment by meffon1** [comment]
Use the [Gesior](https://github.com/jlcvp/GesiorMonteiro) ang [Login.php](https://gist.github.com/jlcvp/2f1772cbbcdfc966ee982985326d964a)
And say what happens

**What version of znote are you using?**
